"use client";
import { branchesForEntity, Field, FormActions } from "./student-operations-form-shared";
export function EnrolmentForm({ form, setForm, students, programmes, intakes, branches, entities, profiles, errors, onSubmit, onCancel, busy }) {
const entityStudents = students.filter((student) => !form.entity_id || student.entity_id === form.entity_id);
const entityProgrammes = programmes.filter((programme) => !form.entity_id || programme.entity_id === form.entity_id);
const programmeIntakes = intakes.filter((intake) => !form.programme_id || intake.programme_id === form.programme_id);
const entityBranches = branchesForEntity(branches, entities, form.entity_id);
return (<form onSubmit={onSubmit} noValidate>
<p className="form-guidance wide">Required relationships are marked with an asterisk. Counsellor and registration-payment details are optional.</p>
<Field name="student_id" label="Student" required error={errors.student_id}><select value={form.student_id} onChange={(event) => { const student = students.find((item) => item.id === event.target.value); setForm({ ...form, student_id: event.target.value, entity_id: student?.entity_id || form.entity_id, programme_id: "", intake_id: "", branch_id: "" }); }}><option value="">Choose student</option>{entityStudents.map((student) => <option key={student.id} value={student.id}>{student.student_number} - {student.full_name}</option>)}</select></Field>
<Field name="programme_id" label="Programme" required error={errors.programme_id}><select value={form.programme_id} onChange={(event) => { const programme = programmes.find((item) => item.id === event.target.value); setForm({ ...form, programme_id: event.target.value, entity_id: programme?.entity_id || form.entity_id, intake_id: "", branch_id: "" }); }}><option value="">Choose programme</option>{entityProgrammes.map((programme) => <option key={programme.id} value={programme.id}>{programme.programme_code} - {programme.programme_name}</option>)}</select></Field>
<Field name="intake_id" label="Intake" required error={errors.intake_id}><select value={form.intake_id} onChange={(event) => { const intake = intakes.find((item) => item.id === event.target.value); setForm({ ...form, intake_id: event.target.value, entity_id: intake?.entity_id || form.entity_id, branch_id: intake?.branch_id || form.branch_id, expected_completion_date: intake?.expected_completion_date || form.expected_completion_date }); }}><option value="">Choose intake</option>{programmeIntakes.map((intake) => <option key={intake.id} value={intake.id}>{intake.intake_code} - {branches.find((branch) => branch.id === intake.branch_id)?.branch_code || ""}</option>)}</select></Field>
<Field name="branch_id" label="Branch" required error={errors.branch_id}><select value={form.branch_id} onChange={(event) => setForm({ ...form, branch_id: event.target.value })} disabled={Boolean(form.intake_id)}><option value="">Choose branch</option>{entityBranches.map((branch) => <option key={branch.id} value={branch.id}>{branch.branch_code} - {branch.branch_name}</option>)}</select></Field>
<Field name="enrolment_date" label="Enrolment date" required error={errors.enrolment_date}><input type="date" value={form.enrolment_date || ""} onChange={(event) => setForm({ ...form, enrolment_date: event.target.value })}/></Field>
<Field name="status" label="Record status" error={errors.status}><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}>{["draft", "applied", "enrolled", "active", "deferred", "transferred", "completed", "withdrawn", "cancelled", "inactive"].map((status) => <option key={status} value={status}>{status}</option>)}</select></Field>
<Field name="counsellor_user_id" label="Linked counsellor profile" optional error={errors.counsellor_user_id}><select value={form.counsellor_user_id || ""} onChange={(event) => { const profile = profiles.find((item) => item.id === event.target.value); setForm({ ...form, counsellor_user_id: event.target.value, counsellor_name_snapshot: profile?.display_name || form.counsellor_name_snapshot }); }}><option value="">Not linked to a login</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.display_name || profile.email}</option>)}</select></Field>
<Field name="counsellor_name_snapshot" label="+ Add counsellor / external agent name" optional error={errors.counsellor_name_snapshot}><input value={form.counsellor_name_snapshot || ""} onChange={(event) => setForm({ ...form, counsellor_name_snapshot: event.target.value })} placeholder="Ms Hailey, Ms Chong, external agent..."/></Field>
<Field name="expected_completion_date" label="Expected completion" optional error={errors.expected_completion_date}><input type="date" value={form.expected_completion_date || ""} onChange={(event) => setForm({ ...form, expected_completion_date: event.target.value })}/></Field>
<Field name="referral_source" label="Referral/source" optional error={errors.referral_source}><input value={form.referral_source || ""} onChange={(event) => setForm({ ...form, referral_source: event.target.value })}/></Field>
<h3 className="form-section-title wide">Interim registration payment</h3>
<p className="help wide">Stage 1A operational snapshot only. It can be migrated into the structured Stage 1B fee-item and payment model later.</p>
<Field name="registration_fee_amount" label="Registration fee amount" optional error={errors.registration_fee_amount}><input type="number" min="0" step="0.01" value={form.registration_fee_amount || ""} onChange={(event) => setForm({ ...form, registration_fee_amount: event.target.value })}/></Field>
<Field name="registration_fee_paid_amount" label="Registration fee paid amount" optional error={errors.registration_fee_paid_amount}><input type="number" min="0" step="0.01" value={form.registration_fee_paid_amount || ""} onChange={(event) => setForm({ ...form, registration_fee_paid_amount: event.target.value })}/></Field>
<Field name="registration_payment_date" label="Payment date" optional error={errors.registration_payment_date}><input type="date" value={form.registration_payment_date || ""} onChange={(event) => setForm({ ...form, registration_payment_date: event.target.value })}/></Field>
<Field name="registration_payment_status" label="Registration payment status" error={errors.registration_payment_status}><select value={form.registration_payment_status || "not_paid"} onChange={(event) => setForm({ ...form, registration_payment_status: event.target.value })}>{["not_paid", "partially_paid", "paid", "waived", "pending_confirmation"].map((status) => <option key={status} value={status}>{status}</option>)}</select></Field>
<Field name="registration_payment_method" label="Payment method" optional error={errors.registration_payment_method}><input value={form.registration_payment_method || ""} onChange={(event) => setForm({ ...form, registration_payment_method: event.target.value })} placeholder="Cash, transfer, card..."/></Field>
<Field name="registration_payment_reference" label="Payment reference" optional error={errors.registration_payment_reference}><input value={form.registration_payment_reference || ""} onChange={(event) => setForm({ ...form, registration_payment_reference: event.target.value })}/></Field>
<Field name="registration_payment_remarks" label="Registration payment remarks" optional error={errors.registration_payment_remarks} wide><textarea value={form.registration_payment_remarks || ""} onChange={(event) => setForm({ ...form, registration_payment_remarks: event.target.value })}/></Field>
<Field name="remarks" label="Enrolment remarks" optional error={errors.remarks} wide><textarea value={form.remarks || ""} onChange={(event) => setForm({ ...form, remarks: event.target.value })}/></Field>
<FormActions busy={busy} onCancel={onCancel}/>
</form>);
}
