"use client";

import "./student-operations-uat.css";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AuthBar } from "@/app/auth-bar";
import { EnrolmentForm, IntakeForm, ProgrammeForm, StudentForm } from "@/app/student-operations-forms";
import { ActionGroup, PageTabs, StatusBadge } from "@/app/ui-v2";
import { createClient } from "@/lib/supabase/client";

type Row = Record<string, any>;
type Mode = "dashboard" | "students" | "student-form" | "student-detail" | "programmes" | "intakes" | "enrolments" | "enrolment-form";
type FormKind = "student" | "programme" | "intake" | "enrolment";
type FieldErrors = Record<string, string>;

const today = new Date().toISOString().slice(0, 10);
const NATIONALITIES = ["Malaysian", "Japanese", "Korean", "Chinese", "Indonesian", "Vietnamese", "Filipino", "Thai", "Singaporean", "Kazakhstani"];
const EDUCATION_LEVELS = ["SPM", "UEC", "O Level", "A Level", "STPM", "Certificate", "Diploma", "Advanced Diploma", "Degree", "Master's Degree", "Other"];
const MALAYSIAN_STATES = ["Johor", "Kedah", "Kelantan", "Melaka", "Negeri Sembilan", "Pahang", "Perak", "Perlis", "Pulau Pinang", "Sabah", "Sarawak", "Selangor", "Terengganu", "Kuala Lumpur", "Labuan", "Putrajaya"];
const IETA_STUDENT_BRANCH_CODES = ["KL", "PG"];

const blankStudent = {
  id: "", entity_id: "", full_name: "", preferred_name: "", identity_document_type: "ic", identity_number_protected: "", nationality: "Malaysian", _nationality_other: false, date_of_birth: "", gender: "", phone: "", email: "", address: "", emergency_contact_name: "", emergency_contact_phone: "", emergency_contact_relationship: "", previous_school: "", education_level: "", qualification_details: "", education_institution: "", field_of_study: "", graduation_year: "", home_branch_id: "", city: "", state: "", postcode: "", country: "Malaysia", height_cm: "", weight_kg: "", uniform_size: "", measurement_date: "", measurement_remarks: "", lifecycle_status: "draft", remarks: "",
};
const blankProgramme = { id: "", entity_id: "", programme_code: "", programme_name: "", description: "", programme_type: "", duration_value: "", duration_max_value: "", duration_unit: "months", indicative_standard_fee: "", record_status: "draft" };
const blankIntake = { id: "", programme_id: "", entity_id: "", branch_id: "", intake_code: "", intake_name: "", start_date: "", expected_completion_date: "", original_expected_completion_date: "", application_closing_date: "", actual_completion_date: "", capacity: "", status: "planning", completion_timing: "not_applicable", completion_reason: "", _completion_manual: false, remarks: "" };
const blankEnrolment = { id: "", student_id: "", programme_id: "", intake_id: "", entity_id: "", branch_id: "", counsellor_user_id: "", counsellor_name_snapshot: "", enrolment_date: today, expected_completion_date: "", status: "enrolled", referral_source: "", registration_fee_amount: "", registration_fee_paid_amount: "", registration_payment_date: "", registration_payment_method: "", registration_payment_reference: "", registration_payment_remarks: "", registration_payment_status: "not_paid", remarks: "" };

const csvValue = (value: unknown) => `"${String(value ?? "").replaceAll("\"", "\"\"")}"`;
function branchesForEntity(branches: Row[], entities: Row[], entityId: string) { const entity = entities.find((item) => item.id === entityId); return branches.filter((branch) => branch.entity_id === entityId && (entity?.short_code !== "IETA" || IETA_STUDENT_BRANCH_CODES.includes(branch.branch_code))); }

export function StudentOperationsWorkspace({ mode, id, initialStudentId, initialEnrolmentId }: { mode: Mode; id?: string; initialStudentId?: string; initialEnrolmentId?: string }) {
  const db = useMemo(() => createClient(), []);
  const [message, setMessage] = useState("Loading Student Operations..."); const [error, setError] = useState("");
  const [fieldErrors, setFieldErrors] = useState<Record<FormKind, FieldErrors>>({ student: {}, programme: {}, intake: {}, enrolment: {} });
  const [busy, setBusy] = useState(false); const [entities, setEntities] = useState<Row[]>([]); const [branches, setBranches] = useState<Row[]>([]); const [profiles, setProfiles] = useState<Row[]>([]); const [students, setStudents] = useState<Row[]>([]); const [programmes, setProgrammes] = useState<Row[]>([]); const [intakes, setIntakes] = useState<Row[]>([]); const [enrolments, setEnrolments] = useState<Row[]>([]); const [duplicates, setDuplicates] = useState<Row[]>([]);
  const [filters, setFilters] = useState({ q: "", entity_id: "", branch_id: "", status: "" }); const [studentForm, setStudentForm] = useState<Row>(blankStudent); const [programmeForm, setProgrammeForm] = useState<Row>(blankProgramme); const [intakeForm, setIntakeForm] = useState<Row>(blankIntake); const [enrolmentForm, setEnrolmentForm] = useState<Row>(blankEnrolment); const [mergeTargetId, setMergeTargetId] = useState(""); const [mergeReason, setMergeReason] = useState(""); const [studentDetailTab, setStudentDetailTab] = useState("profile"); const [showStudentEditor, setShowStudentEditor] = useState(mode === "student-form"); const [lastSavedEnrolmentId, setLastSavedEnrolmentId] = useState("");
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (mode === "student-detail" && id && students.length) { const row = students.find((item) => item.id === id); if (row) setStudentForm({ ...blankStudent, ...row, identity_number_protected: "", emergency_contact_name: row.emergency_contact?.name || "", emergency_contact_phone: row.emergency_contact?.phone || "", emergency_contact_relationship: row.emergency_contact?.relationship || "" }); } }, [mode, id, students]);
  useEffect(() => { if (mode === "student-detail" && window.location.hash === "#edit-student") setShowStudentEditor(true); }, [mode]);
  useEffect(() => { if (mode !== "enrolment-form") return; if (initialEnrolmentId && enrolments.length) { const row = enrolments.find((item) => item.id === initialEnrolmentId); if (row) setEnrolmentForm({ ...blankEnrolment, ...row, registration_fee_amount: row.registration_fee_amount || "", registration_fee_paid_amount: row.registration_fee_paid_amount || "" }); return; } if (initialStudentId) setEnrolmentForm((form) => ({ ...form, student_id: initialStudentId })); }, [mode, initialStudentId, initialEnrolmentId, enrolments]);
  async function load() { setError(""); const [entityRes, branchRes, profileRes, studentRes, programmeRes, intakeRes, enrolmentRes, duplicateRes] = await Promise.all([db.from("entities").select("id, short_code, display_name").eq("active_status", true).order("short_code"), db.from("branches").select("*").eq("active_status", true).order("branch_code"), db.from("app_profiles").select("id, display_name, email, role").eq("active_status", true).in("role", ["counsellor", "student_services", "marketing", "branch_manager"]).order("display_name"), db.from("students_staff_safe").select("*").eq("is_demo", false).order("created_at", { ascending: false }), db.from("programmes").select("*").eq("is_demo", false).order("programme_code"), db.from("programme_intakes").select("*").eq("is_demo", false).order("start_date", { ascending: false }), db.from("enrolments_staff_safe").select("*").eq("is_demo", false).order("created_at", { ascending: false }), db.from("student_duplicate_warning_view").select("*")]); const firstError = entityRes.error || branchRes.error || profileRes.error || studentRes.error || programmeRes.error || intakeRes.error || enrolmentRes.error || duplicateRes.error; if (firstError) { console.error("Student Operations load failed", firstError); setError("Student Operations could not be loaded. Please refresh after applying the latest migration."); setMessage("Apply migrations through 0018 before testing this Stage 1A repair."); return; } setEntities(entityRes.data ?? []); setBranches(branchRes.data ?? []); setProfiles(profileRes.data ?? []); setStudents(studentRes.data ?? []); setProgrammes(programmeRes.data ?? []); setIntakes(intakeRes.data ?? []); setEnrolments(enrolmentRes.data ?? []); setDuplicates(duplicateRes.data ?? []); setMessage("Student Operations Stage 1A ready: student master, programmes, intakes and enrolments."); setDefaultEntity(entityRes.data ?? [], branchRes.data ?? []); }
  function setDefaultEntity(nextEntities: Row[], nextBranches: Row[]) { const ieta = nextEntities.find((entity) => entity.short_code === "IETA") || nextEntities[0]; const entityId = ieta?.id || ""; const studentBranches = branchesForEntity(nextBranches, nextEntities, entityId); const firstBranch = studentBranches.find((branch) => branch.branch_code === "KL")?.id || studentBranches[0]?.id || ""; setFilters((current) => current.entity_id ? current : { ...current, entity_id: entityId }); setStudentForm((form) => form.entity_id ? form : { ...form, entity_id: entityId, home_branch_id: firstBranch }); setProgrammeForm((form) => form.entity_id ? form : { ...form, entity_id: entityId }); setIntakeForm((form) => form.entity_id ? form : { ...form, entity_id: entityId, branch_id: firstBranch }); setEnrolmentForm((form) => form.entity_id ? form : { ...form, entity_id: entityId, branch_id: firstBranch }); }
  const scopedBranches = filters.entity_id ? branchesForEntity(branches, entities, filters.entity_id) : branches.filter((branch) => { const entity = entities.find((item) => item.id === branch.entity_id); return entity?.short_code !== "IETA" || IETA_STUDENT_BRANCH_CODES.includes(branch.branch_code); });
  function matchesFilters(row: Row, keys: string[]) { const q = filters.q.toLowerCase().trim(); return (!q || keys.some((key) => String(row[key] || "").toLowerCase().includes(q))) && (!filters.entity_id || row.entity_id === filters.entity_id) && (!filters.branch_id || row.branch_id === filters.branch_id || row.home_branch_id === filters.branch_id) && (!filters.status || row.status === filters.status || String(row.active_status) === filters.status || row.lifecycle_status === filters.status); }
  const filteredStudents = students.filter((student) => matchesFilters(student, ["full_name", "student_number", "email", "phone"])); const filteredProgrammes = programmes.filter((programme) => matchesFilters(programme, ["programme_code", "programme_name", "programme_type"])); const filteredIntakes = intakes.filter((intake) => matchesFilters(intake, ["intake_code", "intake_name", "status"])); const filteredEnrolments = enrolments.filter((enrolment) => matchesFilters(enrolment, ["enrolment_number", "student_name", "programme_name", "intake_code", "status"])); const selectedStudent = id ? students.find((student) => student.id === id) : undefined; const selectedStudentEnrolments = selectedStudent ? enrolments.filter((row) => row.student_id === selectedStudent.id) : []; const selectedStudentDuplicates = selectedStudent ? duplicates.filter((row) => row.student_id === selectedStudent.id || row.possible_duplicate_student_id === selectedStudent.id) : [];
  function branchLabel(branchId: string) { const branch = branches.find((item) => item.id === branchId); return branch ? `${branch.branch_code} - ${branch.branch_name}` : ""; } function programmeLabel(programmeId: string) { const programme = programmes.find((item) => item.id === programmeId); return programme ? `${programme.programme_code} - ${programme.programme_name}` : ""; }
  function resetStudent() { const ieta = entities.find((entity) => entity.short_code === "IETA") || entities[0]; const branchOptions = branchesForEntity(branches, entities, ieta?.id || ""); setStudentForm({ ...blankStudent, entity_id: ieta?.id || "", home_branch_id: branchOptions.find((branch) => branch.branch_code === "KL")?.id || branchOptions[0]?.id || "" }); setMessage("New student form ready."); }
  function saveAction(event: FormEvent) { const submitter = (event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null; return submitter?.value === "draft" ? "draft" : "continue"; }
  function showSaveError(kind: FormKind, response: { error?: string; field_errors?: FieldErrors }, fallback: string) { const supplied = response.field_errors || {}; const nextErrors = Object.keys(supplied).length ? supplied : kind === "enrolment" ? { intake_id: "The enrolment could not be validated. Please reselect the programme and intake, then save again." } : supplied; setFieldErrors((current) => ({ ...current, [kind]: nextErrors })); setError(response.error || fallback); const firstField = Object.keys(nextErrors)[0]; if (!firstField) return; requestAnimationFrame(() => { const wrapper = document.querySelector<HTMLElement>(`[data-field="${firstField}"]`); wrapper?.scrollIntoView({ behavior: "smooth", block: "center" }); wrapper?.querySelector<HTMLElement>("input, select, textarea, button")?.focus(); }); }
  async function saveStudent(event: FormEvent) { event.preventDefault(); const action = saveAction(event); setBusy(true); setError(""); setFieldErrors((current) => ({ ...current, student: {} })); const res = await fetch("/api/students/save", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...studentForm, save_action: action, emergency_contact: { name: studentForm.emergency_contact_name, phone: studentForm.emergency_contact_phone, relationship: studentForm.emergency_contact_relationship } }) }); const json = await res.json(); setBusy(false); if (!res.ok) { showSaveError("student", json, "Could not save student."); return; } setMessage(`Student saved as ${json.lifecycle_status}${json.student_number ? ` (${json.student_number})` : ""}. ${json.missing_recommended_fields?.length ? "Recommended information can be added later." : ""}`); await load(); if (!studentForm.id) window.location.assign(action === "draft" ? "/students" : `/students/${json.id}`); }
  async function saveProgramme(event: FormEvent) { event.preventDefault(); const action = saveAction(event); setBusy(true); setError(""); setFieldErrors((current) => ({ ...current, programme: {} })); const res = await fetch("/api/programmes/save", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...programmeForm, save_action: action }) }); const json = await res.json(); setBusy(false); if (!res.ok) { showSaveError("programme", json, "Programme could not be saved."); return; } setMessage("Programme saved."); setProgrammeForm({ ...blankProgramme, entity_id: programmeForm.entity_id }); await load(); }
  async function saveIntake(event: FormEvent) { event.preventDefault(); const action = saveAction(event); setBusy(true); setError(""); setFieldErrors((current) => ({ ...current, intake: {} })); const res = await fetch("/api/intakes/save", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...intakeForm, save_action: action }) }); const json = await res.json(); setBusy(false); if (!res.ok) { showSaveError("intake", json, "Intake could not be saved."); return; } setMessage("Intake saved."); setIntakeForm({ ...blankIntake, entity_id: intakeForm.entity_id, branch_id: intakeForm.branch_id }); await load(); }
  async function saveEnrolment(event: FormEvent) { event.preventDefault(); const action = saveAction(event); setBusy(true); setError(""); setFieldErrors((current) => ({ ...current, enrolment: {} })); const res = await fetch("/api/enrolments/save", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...enrolmentForm, save_action: action }) }); const json = await res.json(); setBusy(false); if (!res.ok) { showSaveError("enrolment", json, "Could not save enrolment."); return; } setLastSavedEnrolmentId(json.id || enrolmentForm.id); setMessage(`Enrolment saved${json.enrolment_number ? ` as ${json.enrolment_number}` : ""}. You can view it under Enrolments.`); setEnrolmentForm({ ...blankEnrolment, entity_id: enrolmentForm.entity_id, branch_id: enrolmentForm.branch_id }); await load(); }
  async function mergeStudent() { if (!selectedStudent || !mergeTargetId || !mergeReason.trim()) { setError("Choose the target student and enter a merge reason first."); return; } if (!window.confirm("Merge this student into the selected target? The source student will be inactive, not deleted.")) return; setBusy(true); const res = await fetch("/api/students/merge", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source_student_id: selectedStudent.id, target_student_id: mergeTargetId, reason: mergeReason }) }); const json = await res.json(); setBusy(false); if (!res.ok) { setError(json.error || "Could not merge students."); return; } setMessage("Students merged. Enrolments and document links were preserved."); await load(); }
  async function studentRecordAction(action: "delete" | "archive" | "duplicate", student: Row) { const needsReason = action !== "delete"; const reason = needsReason ? window.prompt(`Reason to ${action === "duplicate" ? "mark as duplicate" : action} ${student.full_name}:`) : ""; if (needsReason && !reason?.trim()) { setError("A reason is required for the audit trail."); return; } const warning = action === "delete" ? "Delete this draft or incomplete student? Deletion is allowed only when there are no linked records." : `${action === "archive" ? "Archive" : "Mark as duplicate"} this student?`; if (!window.confirm(warning)) return; setBusy(true); setError(""); const res = await fetch("/api/students/record-action", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ studentId: student.id, action, reason }) }); const json = await res.json(); setBusy(false); if (!res.ok) { setError(json.error || "Student action could not be completed."); return; } setMessage(action === "delete" ? "Draft student deleted." : action === "archive" ? "Student archived with audit trail." : "Student marked for duplicate review."); await load(); }
  function exportRows(filename: string, rows: Row[], columns: string[]) { const csv = [columns.join(","), ...rows.map((row) => columns.map((column) => csvValue(row[column])).join(","))].join("\n"); const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
  return <main><div className="page-header"><div><p className="eyebrow">Student Operations</p><h1>{titleFor(mode)}</h1><p className="subtitle">Student master, programmes, intakes and enrolments. Full fee allocation and official receipts remain outside this Stage 1A workspace.</p></div><AuthBar /></div><WorkspaceTabs /><section className={error ? "notice error" : "notice"}><p>{error || message}</p><button className="neutral" onClick={() => void load()} disabled={busy}>Refresh</button></section>{mode === "enrolment-form" && lastSavedEnrolmentId && <div className="statusbar"><span>Enrolment saved. Continue under Enrolments or reopen the saved record.</span><ActionGroup><Link className="action-button neutral" href="/enrolments">View Enrolments</Link><Link className="action-button primary" href={`/enrolments/new?enrolment_id=${lastSavedEnrolmentId}`}>Edit Saved Enrolment</Link></ActionGroup></div>}
  {mode === "dashboard" && <><section className="metric-grid"><Metric label="Students" value={students.length} /><Metric label="Programmes" value={programmes.length} /><Metric label="Intakes" value={intakes.length} /><Metric label="Enrolments" value={enrolments.length} /></section><section className="split-grid"><Panel title="Stage 1A Workflow"><ol className="workflow-list"><li><strong>Create programme master</strong><span>Keep programme definitions entity-level, not permanently branch-specific.</span></li><li><strong>Create branch intake</strong><span>Use intake/offering to record the current IETA student branches: KL or Penang.</span></li><li><strong>Create student master</strong><span>One person profile; branch participation belongs to enrolments.</span></li><li><strong>Create enrolment</strong><span>Generate branch/intake enrolment number and assign counsellor.</span></li></ol></Panel><Panel title="Attention"><Quick href="/students" label="Possible duplicates" detail={`${duplicates.length} warning rows`} /><Quick href="/enrolments" label="Active enrolments" detail={`${enrolments.filter((row) => ["enrolled", "active"].includes(row.status)).length} records`} /><Quick href="/programmes" label="Programmes" detail="Maintain master programme details and indicative defaults" /></Panel></section></>}
  {["students", "programmes", "intakes", "enrolments"].includes(mode) && <Filters filters={filters} setFilters={setFilters} entities={entities} branches={scopedBranches} />}
  {mode === "students" && <section><div className="section-heading"><div><h2>Student list</h2><p className="help">Showing {filteredStudents.length} of {students.length} students, including Draft and Incomplete records.</p></div><ActionGroup><Link className="action-button primary primary-action" href="/students/new">+ New Student</Link><Link className="action-button neutral" href="/students/import">Import Students</Link><button className="neutral" onClick={() => exportRows("students-stage1a.csv", filteredStudents, ["entity_code", "student_number", "full_name", "preferred_name", "identity_number_masked", "phone", "email", "home_branch_code", "lifecycle_status"])}>Export CSV</button></ActionGroup></div><div className="compact-kpis"><span className="kpi-chip">All <strong>{students.length}</strong></span><span className="kpi-chip">Draft <strong>{students.filter((row) => row.lifecycle_status === "draft").length}</strong></span><span className="kpi-chip">Incomplete <strong>{students.filter((row) => row.lifecycle_status === "incomplete").length}</strong></span><span className="kpi-chip">Active <strong>{students.filter((row) => row.lifecycle_status === "active").length}</strong></span></div><StudentListV2 rows={filteredStudents} enrolments={enrolments} onAction={studentRecordAction} /></section>}
  {mode === "student-form" && <Panel title="New Student"><StudentForm form={studentForm} setForm={setStudentForm} entities={entities} branches={branches} errors={fieldErrors.student} onSubmit={saveStudent} onCancel={resetStudent} busy={busy} /></Panel>}
  {mode === "student-detail" && selectedStudent && <StudentProfileV2 student={selectedStudent} enrolments={selectedStudentEnrolments} duplicates={selectedStudentDuplicates} tab={studentDetailTab} setTab={setStudentDetailTab} showEditor={showStudentEditor} setShowEditor={setShowStudentEditor} onAction={studentRecordAction} editor={<StudentForm form={studentForm} setForm={setStudentForm} entities={entities} branches={branches} errors={fieldErrors.student} onSubmit={saveStudent} onCancel={() => setShowStudentEditor(false)} busy={busy} />} duplicateTools={<div className="mini"><label>Merge this student into<select value={mergeTargetId} onChange={(event) => setMergeTargetId(event.target.value)}><option value="">Choose target student</option>{students.filter((row) => row.id !== selectedStudent.id).map((row) => <option key={row.id} value={row.id}>{row.student_number} - {row.full_name}</option>)}</select></label><label>Merge reason<textarea value={mergeReason} onChange={(event) => setMergeReason(event.target.value)} /></label><button className="danger" onClick={() => void mergeStudent()} disabled={busy}>Merge Duplicate</button></div>} />}
  {mode === "student-detail" && !selectedStudent && <p className="empty-state">Student record not found or not available to your role.</p>}
  {mode === "programmes" && <section className="split-grid"><Panel title="Programme Master"><ProgrammeForm form={programmeForm} setForm={setProgrammeForm} entities={entities} errors={fieldErrors.programme} onSubmit={saveProgramme} onCancel={() => setProgrammeForm({ ...blankProgramme, entity_id: programmeForm.entity_id })} busy={busy} /></Panel><Panel title="Programmes"><button className="neutral" onClick={() => exportRows("programmes-stage1a.csv", filteredProgrammes, ["programme_code", "programme_name", "programme_type", "duration_text", "indicative_standard_fee", "record_status"])}>Export CSV</button><Table rows={filteredProgrammes} empty="No programmes yet." columns={[["programme_code", "Code"], ["programme_name", "Programme"], ["programme_type", "Type"], ["duration_text", "Duration"], ["indicative_standard_fee", "Indicative Tuition Fee"], ["record_status", "Status"]]} action={(row) => <button className="neutral" onClick={() => setProgrammeForm({ ...blankProgramme, ...row, duration_value: row.duration_value || row.duration_min_value || "", duration_max_value: row.duration_max_value || "" })}>Edit</button>} /></Panel></section>}
  {mode === "intakes" && <section className="split-grid"><Panel title="Programme Intake / Offering"><IntakeForm form={intakeForm} setForm={setIntakeForm} programmes={programmes} branches={branches} entities={entities} errors={fieldErrors.intake} onSubmit={saveIntake} onCancel={() => setIntakeForm({ ...blankIntake, entity_id: intakeForm.entity_id, branch_id: intakeForm.branch_id })} busy={busy} /></Panel><Panel title="Intakes"><button className="neutral" onClick={() => exportRows("intakes-stage1a.csv", filteredIntakes.map((row) => ({ ...row, programme: programmeLabel(row.programme_id), branch: branchLabel(row.branch_id) })), ["programme", "branch", "intake_code", "start_date", "original_expected_completion_date", "expected_completion_date", "actual_completion_date", "status", "completion_timing", "capacity"])}>Export CSV</button><Table rows={filteredIntakes} empty="No intakes yet." columns={[["intake_code", "Intake"], ["start_date", "Start"], ["expected_completion_date", "Current Completion"], ["status", "Operational Status"], ["completion_timing", "Completion Timing"], ["capacity", "Capacity"]]} action={(row) => <button className="neutral" onClick={() => setIntakeForm({ ...blankIntake, ...row, capacity: row.capacity || "", _completion_manual: true })}>Edit</button>} /></Panel></section>}
  {mode === "enrolments" && <section><div className="section-heading"><div><h2>Enrolment list</h2><p className="help">Open or edit an enrolment without searching through the student form.</p></div><ActionGroup><Link className="action-button primary primary-action" href="/enrolments/new">+ New Enrolment</Link><button className="neutral" onClick={() => exportRows("enrolments-stage1a.csv", filteredEnrolments, ["entity_code", "branch_code", "enrolment_number", "student_name", "programme_code", "programme_name", "intake_code", "counsellor_name", "enrolment_date", "status"])}>Export CSV</button></ActionGroup></div><EnrolmentListV2 rows={filteredEnrolments} /></section>}
  {mode === "enrolment-form" && <section className="split-grid"><Panel title={enrolmentForm.id ? "Edit Enrolment" : "New Enrolment"}><EnrolmentForm form={enrolmentForm} setForm={setEnrolmentForm} students={students} programmes={programmes} intakes={intakes} branches={branches} entities={entities} profiles={profiles} errors={fieldErrors.enrolment} onSubmit={saveEnrolment} onCancel={() => setEnrolmentForm({ ...blankEnrolment, entity_id: enrolmentForm.entity_id, branch_id: enrolmentForm.branch_id })} busy={busy} /></Panel><Panel title="Numbering"><p><strong>Student master number</strong></p><p className="tag">IETA-STU-26-0001</p><p className="help">Permanent internal student-master identifier. It does not change when the student changes branch or programme.</p><p><strong>Student enrolment / ID card number</strong></p><p className="tag">IETA-KL26/ID32-001</p><p className="help">Generated atomically when an enrolment is created. A second programme creates a second enrolment number while retaining the same student master.</p><Link className="button-link neutral" href="/enrolments">Back to Enrolments</Link></Panel></section>}
  </main>;
}
function titleFor(mode: Mode) { if (mode === "students") return "Students"; if (mode === "student-form") return "New Student"; if (mode === "student-detail") return "Student Detail"; if (mode === "programmes") return "Programmes"; if (mode === "intakes") return "Intakes"; if (mode === "enrolments") return "Enrolments"; if (mode === "enrolment-form") return "New Enrolment"; return "Student Operations Dashboard"; }
function WorkspaceTabs() { const tabs = [["/student-operations", "Dashboard"], ["/students", "Students"], ["/programmes", "Programmes"], ["/intakes", "Intakes"], ["/enrolments", "Enrolments"]]; return <nav>{tabs.map(([href, label]) => <Link key={href} href={href}>{label}</Link>)}</nav>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel"><h2>{title}</h2>{children}</section>; }
function Quick({ href, label, detail }: { href: string; label: string; detail: string }) { return <Link className="inline-card" href={href}><strong>{label}</strong><span>{detail}</span><span>Open</span></Link>; }

function StudentListV2({ rows, enrolments, onAction }: { rows: Row[]; enrolments: Row[]; onAction: (action: "delete" | "archive" | "duplicate", student: Row) => void }) {
  if (!rows.length) return <p className="empty-state">No students match the current filters. Clear the filters or create a new student.</p>;
  return <div className="record-list student-record-list">
    <div className="record-list-head"><span>Student No</span><span>Student</span><span>Programme / Intake</span><span>Status</span><span>Updated</span><span>Actions</span></div>
    {rows.map((student) => {
      const studentEnrolments = enrolments.filter((row) => row.student_id === student.id);
      const current = studentEnrolments.find((row) => ["active", "enrolled"].includes(row.status)) || studentEnrolments[0];
      return <div className="record-row" key={student.id}><div className="record-row-main">
        <div className="record-primary"><strong>{student.student_number || "Pending number"}</strong><span>{student.home_branch_code || "No branch"}</span></div>
        <div className="record-primary"><strong>{student.full_name}</strong><span>{[student.nationality, student.student_category].filter(Boolean).join(" · ") || "Category not recorded"}</span></div>
        <div className="record-primary"><strong>{current?.programme_name || "Not enrolled"}</strong><span>{current ? `${current.intake_code || "No intake"} · ${current.branch_code || ""}` : "Add an enrolment when ready"}</span></div>
        <StatusBadge status={student.lifecycle_status} />
        <div className="record-secondary">{formatDate(student.updated_at || student.created_at)}</div>
        <ActionGroup>
          <Link className="action-button neutral" href={`/students/${student.id}`}>Open / View</Link>
          <Link className="action-button primary" href={`/students/${student.id}#edit-student`}>Edit</Link>
          <Link className="action-button neutral" href={`/enrolments/new?student_id=${student.id}`}>Enrol</Link>
          {student.lifecycle_status !== "archived" && <button type="button" className="neutral" onClick={() => void onAction("archive", student)}>Archive</button>}
          <button type="button" className="neutral" onClick={() => void onAction("duplicate", student)}>Mark Duplicate</button>
          {["draft", "incomplete"].includes(student.lifecycle_status) && <button type="button" className="danger" onClick={() => void onAction("delete", student)}>Delete</button>}
        </ActionGroup>
      </div></div>;
    })}
  </div>;
}

function StudentProfileV2({ student, enrolments, duplicates, tab, setTab, showEditor, setShowEditor, onAction, editor, duplicateTools }: Row) {
  const tabs = [{ id: "profile", label: "Profile" }, { id: "enrolments", label: "Enrolments", count: enrolments.length }, { id: "documents", label: "Documents" }, { id: "history", label: "Notes / History", count: duplicates.length }];
  return <section>
    <div className="profile-summary"><div><p className="eyebrow">{student.student_number || "Student record"}</p><h2>{student.full_name}</h2><p>{student.preferred_name ? `Preferred name: ${student.preferred_name}` : "No preferred name recorded"}</p></div><ActionGroup><StatusBadge status={student.lifecycle_status} /><button type="button" className="primary" onClick={() => setShowEditor(!showEditor)}>Edit Student</button><Link className="action-button neutral" href={`/enrolments/new?student_id=${student.id}`}>+ Add Enrolment</Link><button type="button" className="neutral" onClick={() => void onAction("archive", student)}>Archive</button><button type="button" className="neutral" onClick={() => void onAction("duplicate", student)}>Mark Duplicate</button>{["draft", "incomplete"].includes(student.lifecycle_status) && <button type="button" className="danger" onClick={() => void onAction("delete", student)}>Delete</button>}</ActionGroup></div>
    <PageTabs tabs={tabs} active={tab} onChange={setTab} label="Student profile sections" />
    {tab === "profile" && <>
      <div className="profile-sections">
        <section className="profile-section-card"><h3>Personal details</h3><dl><ProfileRow label="Full name" value={student.full_name} /><ProfileRow label="Preferred name" value={student.preferred_name} /><ProfileRow label="IC / Passport" value={student.identity_number_masked} /><ProfileRow label="Nationality" value={student.nationality} /><ProfileRow label="Gender" value={student.gender} /><ProfileRow label="Date of birth" value={student.date_of_birth} /><ProfileRow label="Home branch" value={student.home_branch_code} /></dl></section>
        <section className="profile-section-card"><h3>Contact details</h3><dl><ProfileRow label="Phone" value={student.phone} /><ProfileRow label="Email" value={student.email} /><ProfileRow label="Address" value={student.address} /><ProfileRow label="City / State" value={[student.city, student.state].filter(Boolean).join(", ")} /><ProfileRow label="Postcode / Country" value={[student.postcode, student.country].filter(Boolean).join(" · ")} /></dl></section>
        <section className="profile-section-card"><h3>Education</h3><dl><ProfileRow label="Level" value={student.education_level} /><ProfileRow label="Institution" value={student.education_institution || student.previous_school} /><ProfileRow label="Qualification" value={student.qualification_details} /><ProfileRow label="Field of study" value={student.field_of_study} /></dl></section>
        <section className="profile-section-card"><h3>Measurements</h3><dl><ProfileRow label="Height" value={student.height_cm ? `${student.height_cm} cm` : ""} /><ProfileRow label="Weight" value={student.weight_kg ? `${student.weight_kg} kg` : ""} /><ProfileRow label="Uniform size" value={student.uniform_size} /><ProfileRow label="Measured" value={student.measurement_date} /></dl></section>
      </div>
      {student.missing_recommended_fields?.length > 0 && <div className="missing-fields"><strong>Recommended information still missing</strong><ul>{student.missing_recommended_fields.map((field: string) => <li key={field}>{field}</li>)}</ul></div>}
    </>}
    {tab === "enrolments" && <><div className="section-heading"><h3>Enrolment history</h3><Link className="button-link primary" href={`/enrolments/new?student_id=${student.id}`}>+ Add Enrolment</Link></div><EnrolmentListV2 rows={enrolments} /></>}
    {tab === "documents" && <div className="panel"><h2>Student documents</h2><p className="help">Student documents remain in the existing private Documents module. No document fields or files have been moved.</p><Link className="button-link neutral" href="/documents">Open Documents</Link></div>}
    {tab === "history" && <><div className="profile-section-card"><h3>Remarks</h3><p>{student.remarks || "No remarks recorded."}</p><p className="help">Last updated {formatDate(student.updated_at || student.created_at)}</p></div><Panel title="Duplicate Review"><Table rows={duplicates} empty="No duplicate warnings." columns={[["possible_duplicate_student_number", "Possible No."], ["possible_duplicate_name", "Possible Name"], ["match_reason", "Reason"], ["match_strength", "Strength"]]} />{duplicateTools}</Panel></>}
    {showEditor && <section className="panel" id="edit-student"><div className="section-heading"><div><h2>Edit Student</h2><p className="help">All existing student fields remain available.</p></div><button type="button" className="neutral" onClick={() => setShowEditor(false)}>Close Editor</button></div>{editor}</section>}
  </section>;
}

function EnrolmentListV2({ rows }: { rows: Row[] }) {
  if (!rows.length) return <p className="empty-state">No enrolments match this view.</p>;
  return <div className="record-list"><div className="record-list-head"><span>Enrolment No</span><span>Student / Programme</span><span>Intake</span><span>Date</span><span>Status</span><span>Actions</span></div>{rows.map((row) => <div className="record-row" key={row.id}><div className="record-row-main"><div className="record-primary"><strong>{row.enrolment_number || "Draft"}</strong><span>{row.branch_code || "No branch"}</span></div><div className="record-primary"><strong>{row.student_name}</strong><span>{row.programme_name || row.programme_code}</span></div><div className="record-primary"><strong>{row.intake_code || "No intake"}</strong><span>{row.counsellor_name ? `Counsellor: ${row.counsellor_name}` : "No counsellor"}</span></div><div className="record-secondary">{row.enrolment_date}</div><StatusBadge status={row.status} /><ActionGroup><Link className="action-button neutral" href={`/students/${row.student_id}`}>View Student</Link><Link className="action-button primary" href={`/enrolments/new?enrolment_id=${row.id}`}>Edit Enrolment</Link></ActionGroup></div></div>)}</div>;
}

function ProfileRow({ label, value }: { label: string; value: unknown }) { return <div><dt>{label}</dt><dd>{String(value || "—")}</dd></div>; }
function formatDate(value: unknown) { if (!value) return "—"; const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleDateString("en-MY", { day: "2-digit", month: "short", year: "numeric" }); }

function Filters({ filters, setFilters, entities, branches }: { filters: Row; setFilters: (next: any) => void; entities: Row[]; branches: Row[] }) { return <section className="sticky-toolbar"><div className="toolbar-fields"><label>Search<input value={filters.q} onChange={(event) => setFilters({ ...filters, q: event.target.value })} placeholder="Name, number, intake, phone..." /></label><label className="compact">Entity<select value={filters.entity_id} onChange={(event) => setFilters({ ...filters, entity_id: event.target.value, branch_id: "" })}><option value="">All entities</option>{entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.short_code}</option>)}</select></label><label className="compact">Branch<select value={filters.branch_id} onChange={(event) => setFilters({ ...filters, branch_id: event.target.value })}><option value="">All branches</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.branch_code} - {branch.branch_name}</option>)}</select></label><label className="compact">Status<select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="">All statuses</option>{["draft", "incomplete", "active", "inactive", "archived", "planning", "open", "enrolled", "completed"].map((status) => <option key={status} value={status}>{status}</option>)}</select></label></div><button className="neutral" onClick={() => setFilters({ q: "", entity_id: "", branch_id: "", status: "" })}>Clear Filters</button></section>; }
  function Table({ rows, columns, empty, action }: { rows: Row[]; columns: string[][]; empty: string; action?: (row: Row) => React.ReactNode }) { if (!rows.length) return <p className="empty-state">{empty}</p>; return <div className="table-wrap"><table><thead><tr>{columns.map(([key, label]) => <th key={key}>{label}</th>)}{action && <th>Action</th>}</tr></thead><tbody>{rows.map((row) => <tr key={row.id || `${row.student_id}-${row.possible_duplicate_student_id}`}>{columns.map(([key]) => <td key={key}>{formatCell(row[key])}</td>)}{action && <td>{action(row)}</td>}</tr>)}</tbody></table></div>; }
function formatCell(value: unknown) { if (typeof value === "boolean") return value ? "Yes" : "No"; if (typeof value === "number") return value.toLocaleString("en-MY", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); return String(value ?? ""); }
