import { inflateRawSync } from "node:zlib";

export type ImportRow = { rowNumber: number; original: Record<string,string>; mapped: Record<string,unknown>; validationErrors: string[]; duplicateWarnings: unknown[]; requiresConfirmation: boolean; excluded: boolean };
export const templateColumns = ["entity","supplier_name","registration_number","contact_person","email","phone","bank_name","bank_account_number","description","expense_category","fixed_or_variable","expected_amount","frequency","due_day","start_date","end_date","reminder_days","required_document_type","auto_generate_bill","auto_generate_payment_voucher","account_reference_details","account_code_or_SQL_reference","remarks","active_status","applicable_entities"];
export const defaultMapping: Record<string,string> = { company:"entity", entity:"entity", supplier:"supplier_name", payee:"supplier_name", supplier_payee:"supplier_name", supplier_name:"supplier_name", registration_number:"registration_number", contact_person:"contact_person", email:"email", phone:"phone", bank_name:"bank_name", bank_account_number:"bank_account_number", subject_due_date:"description", subject:"description", description:"description", account_details_number:"account_reference_details", amount:"expected_amount", fixed_bill:"fixed_or_variable", variable_bills:"fixed_or_variable", remarks:"remarks", category:"expense_category", expense_category:"expense_category", due_day:"due_day", start_date:"start_date", end_date:"end_date", active_status:"active_status", applicable_entities:"applicable_entities" };
const aliases: Record<string,string> = { iea:"IEA", "inter excel advisory":"IEA", ieta:"IETA", "inter excel tourism academy":"IETA", plc:"PLC", premier:"PLC", "premier language centre":"PLC", kaler:"KALER", "agensi pekerjaan kaler":"KALER" };
const categoryHints: [RegExp,string][] = [[/rent|rental|koswip/i,"Rent"],[/loan|bmw|car/i,"Vehicle Loan"],[/mobile|u mobile|phone|telco|unifi|internet/i,"Telecommunications"],[/parking/i,"Parking"],[/utility|water|electric|tnb/i,"Utilities"],[/kwsp|epf|socso|perkeso|eis/i,"Statutory Payment"]];
export function normalise(v: unknown) { return String(v ?? "").toLowerCase().replace(/sdn\.?\s*bhd\.?|bhd\.?|plc|pte\.?\s*ltd\.?/g, "").replace(/[^a-z0-9]+/g, " ").trim(); }
export function normaliseAccount(v: unknown) { return String(v ?? "").replace(/\D+/g, ""); }
export function inferMapping(headers: string[]) { return Object.fromEntries(headers.map((h) => [h, defaultMapping[toKey(h)] || ""])); }
export function resolveEntityCode(value: unknown, entities: { short_code: string; legal_name?: string; display_name?: string }[]) { const key = normalise(value); if (!key) return ""; const alias = aliases[key]; if (alias && entities.some((e) => e.short_code === alias)) return alias; const found = entities.filter((e) => [e.short_code,e.legal_name,e.display_name].some((x) => normalise(x) === key)); return found.length === 1 ? found[0].short_code : ""; }
export function parseAmount(value: unknown) { const text = String(value ?? "").replace(/rm/gi, "").replace(/,/g, "").replace(/[^\d.-]/g, ""); if (!text) return null; const n = Number(text); return Number.isFinite(n) ? n : null; }
export function parseDueDay(value: unknown) { const m = String(value ?? "").match(/\b(?:due\s*)?([1-9]|[12]\d|3[01])(?:st|nd|rd|th)?\b/i); return m ? Math.min(31, Math.max(1, Number(m[1]))) : null; }
export function parseBoolean(value: unknown, fallback = true) { const text = String(value ?? "").trim().toLowerCase(); return text ? ["yes","y","true","1","active"].includes(text) : fallback; }
export function parseDate(value: unknown) { if (typeof value === "number" && Number.isFinite(value)) return new Date(Date.UTC(1899, 11, 30 + Math.floor(value))).toISOString().slice(0,10); const text = String(value ?? "").trim(); if (!text) return null; const d = new Date(text); return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0,10); }
export function validateMapped(mapped: Record<string,unknown>, entities: { short_code: string }[]) { const errors: string[] = []; if (!resolveEntityCode(mapped.entity, entities)) errors.push("Unknown or ambiguous entity"); if (!String(mapped.supplier_name ?? "").trim()) errors.push("Missing supplier/payee"); if (!String(mapped.description ?? "").trim()) errors.push("Missing description"); if (parseDueDay(mapped.due_day ?? mapped.description) == null) errors.push("Missing or invalid due day"); if (String(mapped.fixed_or_variable ?? "").toLowerCase() !== "variable" && parseAmount(mapped.expected_amount) == null) errors.push("Missing expected amount for fixed obligation"); return errors; }
export function mapRows(rows: Record<string,string>[], mapping: Record<string,string>, entities: { short_code: string }[]): ImportRow[] { return rows.map((row, i) => { const mapped: Record<string,unknown> = {}; for (const [header, field] of Object.entries(mapping)) if (field) mapped[field] = row[header] ?? ""; applyHints(row, mapped); return { rowNumber: i + 2, original: row, mapped, validationErrors: validateMapped(mapped, entities), duplicateWarnings: [], requiresConfirmation: uncertain(row, mapped), excluded: false }; }); }
export function parseCsv(text: string) { const rows: string[][] = []; let cell = "", row: string[] = [], quoted = false; for (let i=0;i<text.length;i++) { const c=text[i], n=text[i+1]; if (c==='"' && quoted && n==='"') { cell+='"'; i++; } else if (c==='"') quoted=!quoted; else if (c===',' && !quoted) { row.push(cell); cell=""; } else if ((c==='\n'||c==='\r') && !quoted) { if (c==='\r'&&n==='\n') i++; row.push(cell); rows.push(row); row=[]; cell=""; } else cell+=c; } row.push(cell); rows.push(row); return tableToObjects(rows); }
export function parseXlsx(buffer: Buffer) { const files = unzip(buffer); const workbook = str(files.get("xl/workbook.xml")); const rels = str(files.get("xl/_rels/workbook.xml.rels")); const shared = sharedStrings(str(files.get("xl/sharedStrings.xml"))); const relMap = new Map<string,string>(); for (const r of rels.matchAll(/<Relationship[^>]+Id="([^"]+)"[^>]+Target="([^"]+)"/g)) relMap.set(r[1], r[2].replace(/^\/?xl\//,"")); const sheets = []; for (const s of workbook.matchAll(/<sheet[^>]+name="([^"]+)"[^>]+r:id="([^"]+)"/g)) { const target = relMap.get(s[2]); if (target) sheets.push({ name: decode(s[1]), rows: parseSheet(str(files.get(`xl/${target}`)), shared) }); } return sheets; }
function applyHints(original: Record<string,string>, mapped: Record<string,unknown>) { const subject = String(mapped.description || original["Subject & Due Date"] || ""); const account = String(mapped.account_reference_details || original["Account Details & Number"] || ""); const fixed = original["Fixed Bill"], variable = original["Variable Bills"]; if (!mapped.fixed_or_variable) mapped.fixed_or_variable = String(variable ?? "").trim() ? "variable" : "fixed"; if (!mapped.expected_amount) mapped.expected_amount = fixed || variable || original.Amount || ""; if (!mapped.due_day) mapped.due_day = parseDueDay(subject) ?? ""; if (!mapped.expense_category) mapped.expense_category = categoryHints.find(([p]) => p.test(`${subject} ${account}`))?.[1] ?? ""; if (!mapped.supplier_name) mapped.supplier_name = inferSupplier(subject); if (!mapped.account_reference_details) mapped.account_reference_details = account; if (!mapped.description) mapped.description = subject; mapped.frequency ||= "monthly"; mapped.reminder_days ||= 3; mapped.required_document_type ||= "payment_voucher"; mapped.auto_generate_bill = mapped.auto_generate_bill || true; mapped.auto_generate_payment_voucher = mapped.auto_generate_payment_voucher || true; mapped.start_date ||= new Date().toISOString().slice(0,10); mapped.active_status = mapped.active_status || true; }
function inferSupplier(subject: string) { return ["KOSWIP","U Mobile","Unifi","TNB","Indah Water","KWSP","SOCSO","PERKESO","CIMB","Public Bank","Maybank","RHB","Hong Leong"].find((x) => new RegExp(`\\b${x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\b`, "i").test(subject)) || ""; }
function uncertain(original: Record<string,string>, mapped: Record<string,unknown>) { const explicit = Object.keys(original).some((h) => /supplier|payee/i.test(h) && String(original[h]).trim()); return !explicit && (!mapped.supplier_name || /rental|loan|utilities|parking|mobile|unifi/i.test(String(mapped.description ?? ""))); }
function toKey(v: string) { return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,""); }
function tableToObjects(table: string[][]) { const start = table.findIndex((r) => r.some((c) => String(c ?? "").trim())); if (start < 0) return []; const headers = table[start].map((c,i) => String(c || `Column ${i+1}`).trim()); return table.slice(start+1).filter((r) => r.some((c) => String(c ?? "").trim())).map((r) => Object.fromEntries(headers.map((h,i) => [h, String(r[i] ?? "").trim()]))); }
function parseSheet(xml: string, shared: string[]) { const rows: string[][] = []; for (const rm of xml.matchAll(/<row[^>]*>([\s\S]*?)<\/row>/g)) { const values: string[] = []; for (const cm of rm[1].matchAll(/<c([^>]*)>([\s\S]*?)<\/c>/g)) { const ref = cm[1].match(/\sr="([A-Z]+)(\d+)"/)?.[1] ?? ""; const idx = ref ? ref.split("").reduce((s,ch)=>s*26+ch.charCodeAt(0)-64,0)-1 : values.length; const type = cm[1].match(/\st="([^"]+)"/)?.[1] ?? ""; values[idx] = type === "s" ? shared[Number(cm[2].match(/<v>([\s\S]*?)<\/v>/)?.[1] ?? 0)] ?? "" : decode(cm[2].match(/<t[^>]*>([\s\S]*?)<\/t>/)?.[1] ?? cm[2].match(/<v>([\s\S]*?)<\/v>/)?.[1] ?? ""); } rows.push(values); } return tableToObjects(rows); }
function sharedStrings(xml: string) { return [...xml.matchAll(/<si[^>]*>([\s\S]*?)<\/si>/g)].map((i) => decode([...i[1].matchAll(/<t[^>]*>([\s\S]*?)<\/t>/g)].map((x) => x[1]).join(""))); }
function unzip(buffer: Buffer) { const files = new Map<string,Buffer>(); let offset = 0; while (offset < buffer.length - 30) { if (buffer.readUInt32LE(offset) !== 0x04034b50) { offset++; continue; } const method = buffer.readUInt16LE(offset+8), size = buffer.readUInt32LE(offset+18), nameLen = buffer.readUInt16LE(offset+26), extraLen = buffer.readUInt16LE(offset+28); const name = buffer.slice(offset+30, offset+30+nameLen).toString("utf8"); const start = offset+30+nameLen+extraLen; const data = buffer.slice(start, start+size); files.set(name, method === 8 ? inflateRawSync(data) : data); offset = start+size; } return files; }
function str(b?: Buffer) { return b?.toString("utf8") ?? ""; }
function decode(v: string) { return v.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'"); }
